config/routes.rb
Rails.application.routes.draw do
  root to: "boards#index"
  # get 'reminders/index'
  resources :reminders do
    
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  #resourse full routes
  resources :home do
    member do
      get :delete
    end
  end

  resources :boards do
    member do
      get :delete
    end
  end

  resources :lists do
    member do
      get :delete
    end
  end
  
  resources :todos do
    member do
      get :delete
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :board
    has_many :todos , dependent: :destroy
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController    
    before_action :authenticate_user!
    load_and_authorize_resource
    
    def index
        @lists = @lists.where(:board_id => params[:board_id])
        @board_id = params[:board_id]
        @title  = @lists.length > 0 ? @lists.first.board.name : "EMPTY BOARD"
        
        @board_id_user = Board.find_by_id(params[:board_id])&.user&.id
        
        if @board_id_user != current_user.id
            flash[:notice] = "You are not allowed to see this board"
            redirect_to(root_path)
        end
        
    end

    def new
        @board_id = params[:format]
    end

    def create
        # load_and_authorize will defaulty look for its list_params
        # @list.user_id = current_user.id will also create user with id 
        #  so we dont have to 
        # @list = List.new(list_params)
        if @list.save
            redirect_to(lists_path(:board_id =>@list.board_id))
        else
            render('new')
        end
    end

    def edit
        # @list = List.find_by_id(params[:id])
    end

    def update
        # @task = List.find_by_id(params[:id])
        if @list.update(list_params)
            redirect_to(lists_path(:board_id => @list.board_id))
        else
            render('edit')
        end
    end
    
    def destroy
        # @task = List.find(params[:id])
        @list.destroy
        flash[:notice] = "Task-List Deleted"
        redirect_to(lists_path(:board_id => @list.board_id))
    end

    private

    def list_params
        params.require(:list).permit(:name ,:board_id)
    end
end

app/views/lists/edit.html.erb
<h>Update name List</h>
<%= form_for(@list) do |f| %>
    <%= f.text_field(:name) %>
    <%= f.submit %>
<%end%>

app/views/lists/index.html.erb
<%= link_to '<<Back' , boards_path%>
<h1> <%= @title %> </h1>
<table>

<tr>

    <% @lists.each do |list| %>
        <th>

            <div class="dropdown">

                <a class = "dropdown-item" href= <%= todos_path(:list_id => list.id)%> > 
                    <h4> <%= list.name %> </h4>
                </a>
                
                <a class = "dropdown-item" href= <%= edit_list_path(list)%> >
                    Edit List
                </a>

                <div data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= button_to "Delete List" , list_path(list) , method: :delete %>
                </div>
    
                <a class = "dropdown-item" href= <%= new_todo_path(:id=> list.id ,:board_id =>@board_id)%> >
                    Add Todo
                </a>
                
            </div>

        </th>

    <%end%>
    
    <th>
        <td> <%= link_to("Create-List" , new_list_path(@board_id))%> </td>
    </th>

</tr>

</table>

app/views/lists/new.html.erb
<h>Create new List</h>
<%= form_for(@list) do |f| %>
    <%= f.text_field(:name) %>
    <%= f.hidden_field(:board_id , :value => @board_id) %>
    <%= f.submit() %>
<%end%>