config/routes.rb
Rails.application.routes.draw do
  root to: "boards#index"
  # get 'reminders/index'
  resources :reminders do
    
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  #resourse full routes
  resources :home do
    member do
      get :delete
    end
  end

  resources :boards do
    member do
      get :delete
    end
  end

  resources :lists do
    member do
      get :delete
    end
  end
  
  resources :todos do
    member do
      get :delete
    end
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Trello</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <% if @notifications_num !=nil %>
            <li class="nav-item">
              <a type="button" class="btn btn-primary" href=<%= reminders_path %>>
                    Notifications 
                  <span class="badge badge-light"><%= @notifications_num %></span>
              </a>
            </li>
          <% end %>

            <li class="nav-item">
              <%= link_to 'Logout' , destroy_user_session_path , class:'nav-link' ,method: :delete %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Register' ,new_user_registration_path, class: 'nav-link' %>
            </li>
            
            <li class="nav-item" >
                <%= link_to 'Sign in' , new_user_session_path , class: 'nav-link' %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>