config/routes.rb
Rails.application.routes.draw do
  root to: "boards#index"
  # get 'reminders/index'
  resources :reminders do
    
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  #resourse full routes
  resources :home do
    member do
      get :delete
    end
  end

  resources :boards do
    member do
      get :delete
    end
  end

  resources :lists do
    member do
      get :delete
    end
  end
  
  resources :todos do
    member do
      get :delete
    end
  end
end

app/models/board.rb
class Board < ApplicationRecord 
    belongs_to :user
    has_many :lists  , dependent: :destroy
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController  
  before_action :authenticate_user!
  load_and_authorize_resource


  def index
    # @boards = User.find_by_id(current_user.id).boards
    @notifications_num = Reminder.where(user_id: current_user.id).count
  end
  
  def new
  end

  def create
    # @board = current_user.boards.new(board_params)  
    if @board.save
      redirect_to(boards_path)
      flash[:notice] ="Board was successfully created"
    else
      flash[:notice] = @board.errors.messages
      render('new')
    end
  end
  
  def destroy
    # @board = Board.find(params[:id])
    @board.destroy
    flash[:notice] = "Board was successfully deleted."
    redirect_to(boards_path)
  end

  private
  
  def board_params
    params.require(:board).permit(:name , :user_id)
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/index.html.erb
<% name = current_user.username %>
<h1>Welcome <%= name%> </h1>

<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 140px;">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    <svg class="bi me-2" width="16" height="16"><use xlink:href="#bootstrap"></use></svg>
    <span class="fs-4",style="display: inline-block">Boards </span>
  </a>

  <hr>

  <div class="Board">
    <% @boards.each do |board| %>
      <table class="table">
        <tr> <%= board.name %> <tr>
        <br>
        <tr> <%= link_to "Show Lists" , lists_path(board_id: board.id) %><tr>
        <br>
        <tr> <%= button_to "Delete" ,board_path(board),  data: { confirm: 'Are you sure you want to delete this alert?' } ,method: :delete %> </tr>
      </table>
        <hr>
    <%end%>
  </div>
    
  <div>
    <%= link_to('New Board' ,new_board_path , class: 'action new')%>
  </div>
  
  <hr>
</div>

app/views/boards/new.html.erb
<%= form_for(@board) do |f|%>
    <%= f.text_field(:name) %>
    <%= f.submit %>
<% end %>

app/views/boards/show.html.erb
<h1>Empty Page</h1>